config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  get 'search', to: 'search#index', as: :search

  concern :commentable do
    resources :comments
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end

      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  resources :questions, concerns: :commentable, shallow: true do
    get 'search', on: :collection
    resources :answers, concerns: :commentable do
      get 'search', on: :collection
    end
  end

  resources :subscriptions, only: [:create, :destroy]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :attachments, as: :attachmentable
  has_many :comments, as: :commentable
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :user
end

app/models/question_form.rb
class QuestionForm
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :id, :title, :body, :file, :user_id

  validates :title, presence: true
  validates :body, presence: true

  def initialize(params = {})
    if params['id']
      @question = Question.find(params['id'])
      @attachments = @question.attachments.first
      self.user_id = @question.user.id
    end
    self.id = params.fetch(:id, '')
    self.title = params.fetch(:title, '')
    self.body = params.fetch(:body, '')
    self.file = params.fetch(:file, '')
  end

  def save
    if valid?
      persist!
      true
    else
      false
    end
  end

  def update
    if valid?
      update_form!
      true
    else
      false
    end
  end

  def persisted?
    false
  end

  def self.model_name
    ActiveModel::Name.new(self, nil, 'Question')
  end

  private

  def persist!
    @question = Question.create!(title: title, body: body, user_id: user_id)
    save_attachments
  end

  def update_form!
    @question.update_attributes(
      title: self.title,
      body: self.body
      )
    update_attachments
  end

  def update_attachments
    return unless file.present?
    @attachments.update_attributes(
      file: self.file
      )
  end

  def save_attachments
    return unless file.present?
    @attachments = @question.attachments.create!(file: file)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question
  end

  def create
    @question = QuestionForm.new(question_params)
    @question.user_id = current_resource_owner.id
    @question.save
    respond_with @question
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @questions = Question.includes(:user).all
    respond_with @questions
  end

  def show
    @answers = @question.answers.includes(:attachments, :comments)
                                .order('id DESC')
    @answer = @question.answers.build
    @answer.attachments.build

    respond_with @question
  end

  def new
    @question = QuestionForm.new
  end

  def edit
    authorize @question
  end

  def create
    @question = QuestionForm.new(question_params)
    @question.user_id = current_user.id
    @question.save

    respond_with @question, location: -> { question_path(Question.last) }
  end

  def update
    @question = QuestionForm.new(question_params.merge(id: params[:id]))
    authorize @question
    @question.update

    respond_with @question, location: -> { question_path(@question.id) }
  end

  def destroy
    authorize @question
    respond_with @question.destroy
  end

  def search
    @results = Question.search(params[:q])
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, :file)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
.search_answer
  h3 Search Answer
  = form_tag search_question_answers_path(@question), method: :get do
    .input-group
      = text_field_tag(:q, params[:q], class: 'form-control')
      span.input-group-btn
        = button_tag 'Search', class: 'btn btn-default'

- @answers.each do |answer|
  .answer id="answer-#{answer.id}"
    p= answer.body
    ul
      - answer.attachments.each do |attach|
        li= link_to attach.file.filename, attach.file.url
    - if user_signed_in? && policy(answer).update?
      = link_to 'Edit answer', '', class: 'edit-answer-link', data: { answer_id: answer.id }
    p
      = simple_form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}", class: 'edit_answer' } do |f|
        = f.label 'Answer'
        = f.input :body, label: ''
        = f.submit 'Save'
    .comments
      = render 'comments/list', parent: answer
    hr

app/views/questions/_form.html.slim
= simple_form_for @question do |f|
  = f.input :title
  = f.input :body
  = f.input :file, as: :file, label: 'Upload Attachment'
  = f.button :submit

app/views/questions/_subscribe.html.slim
= simple_form_for(current_user.subscriptions.build, remote: true) do |f|
  = f.input :question_id, as: :hidden, input_html: { value: @question.id }
  = f.submit 'subscribe', class: 'btn btn-info btn-sm'

app/views/questions/_unsubscribe.html.slim
= simple_form_for(current_user.subscriptions.find_by(question_id: @question), remote: true, method: :delete) do |f|
  = f.submit 'unsubscribe', class: 'btn btn-warning btn-sm'

app/views/questions/edit.html.slim
h1 Edit the question
= render 'form'

app/views/questions/index.html.slim
.search_question
  h3 Search Question
  = form_tag search_questions_path, method: :get do
    .input-group
      = text_field_tag(:q, params[:q], class: 'form-control')
      span.input-group-btn
        = button_tag 'Search', class: 'btn btn-default'

- @questions.each do |q|
  h2= link_to q.title, question_path(q)
  p.text-right.created= "Asked at #{q.created_at.strftime("%b %d, %Y")} by #{q.user.email}"
  hr

app/views/questions/new.html.slim
h1 Create new question
= render 'form'

app/views/questions/search.html.slim
.row
  .col-xs-12
    ul.nav.nav-tabs
      h4.pull-left Search Results
- if @results.empty?
  p.text-info no results...
- @results.each do |result|
  .row
    .col-xs-12
      ul.nav.nav-tabs
        h5= link_to result.title, result
        p= truncate(result.body, length: 200)

app/views/questions/show.html.slim
.question
  h1= @question.title
  p= @question.body
  ul
    - @question.attachments.each do |a|
      li= link_to a.file.filename, a.file.url
  - if user_signed_in? && policy(@question).edit?
    = link_to 'Edit', edit_question_path(@question)
  p.subs= "За вопросом следят #{@question.subscribers.count} человек"
  - if user_signed_in?
    - if current_user.subscribed_questions.include?(@question)
      .subs-button= render 'unsubscribe'
    - else
      .subs-button= render 'subscribe'
  .comments
    = render 'comments/list', parent: @question

hr
.answers
  = render 'answers'

.create-answer
  .answers-errors.alert-danger
  = simple_nested_form_for [@question, @answer], remote: true do |f|
    = f.label 'Answer'
    = f.input :body, label: '', input_html: { id: 'new_answer_body' }
    = f.simple_fields_for :attachments do |a|
      = a.input :file, as: :file, label: 'Upload Attachment'
    p= f.link_to_add 'Add a file', :attachments
    = f.button :submit, class: 'btn btn-success'