config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'questions#index'

  get 'search', to: 'search#index', as: :search

  concern :commentable do
    resources :comments
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end

      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  resources :questions, concerns: :commentable, shallow: true do
    get 'search', on: :collection
    resources :answers, concerns: :commentable do
      get 'search', on: :collection
    end
  end

  resources :subscriptions, only: [:create, :destroy]
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title QnA
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
  nav.navbar.navbar-default role="navigation"
    .container
      .navbar-header
        button.navbar-toggle type="button" data-toggle="collapse" data-target="#navbar-collapsable"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#{root_path}" QnA
      .collapse.navbar-collapse#navbar-collapsable
        ul.nav.navbar-nav
          li
            a href="#{questions_path}" Questions
        ul.nav.navbar-nav.navbar-right align="right"
          = form_tag search_path, method: :get, class: 'navbar-form navbar-right' do
            .input-group
              = text_field_tag(:q, params[:q], class: 'form-control mr-sm-2')
              span.input-group-btn
                = button_tag 'Search', class: 'btn btn-default'
          - if !current_user
            li
              = link_to 'Login', new_user_session_path
            li 
              = link_to 'Registration', new_user_registration_path
          - else
            li
              = link_to 'Logout', destroy_user_session_path, method: :delete


  .container
    - if notice
      p.alert.alert-success= notice
    - if alert
      p.alert.alert-danger= alert
    = yield
 